import type { Fixture, Attachment } from '../types';

// ═══════════════════════════════════════════════════════════
// ATTACHMENTS (reusable modifiers, referenced by fixtures)
// ═══════════════════════════════════════════════════════════

export const attachmentLibrary: Attachment[] = [
  // ── Aputure Bowens-Mount Attachments ──
  {
    id: 'aputure-f10-fresnel',
    name: 'Aputure F10 Fresnel',
    type: 'fresnel',
    mountType: 'bowens',
    beamAngleOverride: 15,
    fieldAngleOverride: 45,
    zoomRangeOverride: [15, 45],
    lensTypeOverride: 'fresnel',
    // Measured with LS 600x Pro at 5600K spot 15°: 137,000 lux @ 1m
    photometricOverride: { lux: 137000, distance: 1, beamAngle: 15, colorTemp: 5600 },
    weightAdditional: 3.85,
  },
  {
    id: 'aputure-hyper-reflector',
    name: 'Aputure Hyper-Reflektor',
    type: 'reflector',
    mountType: 'bowens',
    beamAngleOverride: 55,
    fieldAngleOverride: 80,
    // Measured with LS 600x Pro at 5600K: 16,060 lux @ 1m
    photometricOverride: { lux: 16060, distance: 1, beamAngle: 55, colorTemp: 5600 },
    weightAdditional: 0.5,
  },
  {
    id: 'aputure-light-dome-iii',
    name: 'Aputure Light Dome III',
    type: 'softbox',
    mountType: 'bowens',
    beamAngleOverride: 120,
    fieldAngleOverride: 160,
    beamShapeOverride: 'circular',
    weightAdditional: 2.4,
  },
  {
    id: 'aputure-lantern-90',
    name: 'Aputure Lantern 90',
    type: 'lantern',
    mountType: 'bowens',
    beamAngleOverride: 270,
    fieldAngleOverride: 330,
    beamShapeOverride: 'circular',
    weightAdditional: 0.7,
  },
  {
    id: 'aputure-spotlight-mount',
    name: 'Aputure Spotlight Mount',
    type: 'spotlight',
    mountType: 'bowens',
    beamAngleOverride: 19,
    fieldAngleOverride: 30,
    lensTypeOverride: 'interchangeable',
    beamShapeOverride: 'circular',
    weightAdditional: 4.2,
  },
  {
    id: 'generic-barndoors-bowens',
    name: 'Torblende (Bowens)',
    type: 'barndoors',
    mountType: 'bowens',
    weightAdditional: 0.8,
  },
  {
    id: 'generic-snoot-bowens',
    name: 'Snoot (Bowens)',
    type: 'snoot',
    mountType: 'bowens',
    beamAngleOverride: 10,
    fieldAngleOverride: 18,
    weightAdditional: 0.4,
  },
];

// Helper: get attachments by mount type
export function getAttachmentsForMount(mountType: string): Attachment[] {
  return attachmentLibrary.filter((a) => a.mountType === mountType);
}

export const fixtureLibrary: Fixture[] = [
  // ═══════════════════════════════════════════════════════════
  // PROFILSCHEINWERFER (Ellipsoidal / Profile)
  // Scharfkantige Projektionen, Torblenden, Gobos möglich
  // ═══════════════════════════════════════════════════════════
  {
    id: 'etc-s4-19', name: 'Source Four 19°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 19, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, cri: 100, weight: 7.7, mountType: 'clamp',
    photometric: { lux: 49300, distance: 1, beamAngle: 19, colorTemp: 3200 },
    powerConnector: 'Stage Pin / Schuko', dmxChannels: 0,
  },
  {
    id: 'etc-s4-26', name: 'Source Four 26°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 26, fieldAngle: 38,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, cri: 100, weight: 7.5, mountType: 'clamp',
    photometric: { lux: 26000, distance: 1, beamAngle: 26, colorTemp: 3200 },
  },
  {
    id: 'etc-s4-36', name: 'Source Four 36°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 36, fieldAngle: 52,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, cri: 100, weight: 7.3, mountType: 'clamp',
    photometric: { lux: 13700, distance: 1, beamAngle: 36, colorTemp: 3200 },
  },
  {
    id: 'etc-s4-50', name: 'Source Four 50°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 50, fieldAngle: 70,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, cri: 100, weight: 7.1, mountType: 'clamp',
    photometric: { lux: 7100, distance: 1, beamAngle: 50, colorTemp: 3200 },
  },
  {
    id: 'etc-s4-zoom-15-30', name: 'Source Four Zoom 15–30°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 22, fieldAngle: 35,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [15, 30],
    colorTemp: 3200, cri: 100, weight: 8.6, mountType: 'clamp',
    photometric: { lux: 26000, distance: 1, beamAngle: 22, colorTemp: 3200 },
  },
  {
    id: 'etc-s4-zoom-25-50', name: 'Source Four Zoom 25–50°', manufacturer: 'ETC', category: 'profile',
    wattage: 750, lumens: 17800, beamAngle: 37, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [25, 50],
    colorTemp: 3200, cri: 100, weight: 8.6, mountType: 'clamp',
    photometric: { lux: 13700, distance: 1, beamAngle: 37, colorTemp: 3200 },
  },
  {
    id: 'etc-s4led-s3', name: 'Source Four LED S3', manufacturer: 'ETC', category: 'profile',
    wattage: 150, lumens: 11000, beamAngle: 26, fieldAngle: 38,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 95, weight: 8.4, mountType: 'clamp',
    photometric: { lux: 16000, distance: 1, beamAngle: 26, colorTemp: 5600 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 5,
  },
  {
    id: 'robert-juliat-714', name: '714SX2 Suiveur 2,5kW', manufacturer: 'Robert Juliat', category: 'profile',
    wattage: 2500, lumens: 68000, beamAngle: 8, fieldAngle: 16,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [8, 16],
    colorTemp: 3200, weight: 23, mountType: 'yoke',
  },

  // ═══════════════════════════════════════════════════════════
  // STUFENLINSEN (Fresnel)
  // Weicher Rand, stufenlose Fokussierung, Washlicht
  // ═══════════════════════════════════════════════════════════
  {
    id: 'fresnel-1kw', name: '1 kW Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 1000, lumens: 20000, beamAngle: 15, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 55],
    colorTemp: 3200, weight: 5.5, mountType: 'clamp',
  },
  {
    id: 'fresnel-2kw', name: '2 kW Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 2000, lumens: 44000, beamAngle: 12, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 60],
    colorTemp: 3200, weight: 10.2, mountType: 'clamp',
  },
  {
    id: 'etc-cs-fresnel', name: 'ColorSource Fresnel', manufacturer: 'ETC', category: 'fresnel',
    wattage: 125, lumens: 3250, beamAngle: 15, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 50],
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 92, weight: 5.2, mountType: 'clamp',
    dmxChannels: 5,
  },

  // ═══════════════════════════════════════════════════════════
  // PAR-SCHEINWERFER
  // CP62=NSP (kreisrund), CP61=MFL (elliptisch!), CP60=WFL (elliptisch!)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'par64-cp62-nsp', name: 'PAR64 CP62 (NSP)', manufacturer: 'Generic', category: 'par',
    wattage: 1000, lumens: 33000, beamAngle: 12, fieldAngle: 24,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 3.5, mountType: 'clamp',
  },
  {
    id: 'par64-cp61-mfl', name: 'PAR64 CP61 (MFL)', manufacturer: 'Generic', category: 'par',
    wattage: 1000, lumens: 33000, beamAngle: 21, fieldAngle: 28,
    beamShape: 'elliptical', beamRatioWH: 2.0, lensType: 'reflector',
    colorTemp: 3200, weight: 3.5, mountType: 'clamp',
  },
  {
    id: 'par64-cp60-wfl', name: 'PAR64 CP60 (WFL)', manufacturer: 'Generic', category: 'par',
    wattage: 1000, lumens: 33000, beamAngle: 48, fieldAngle: 70,
    beamShape: 'elliptical', beamRatioWH: 1.7, lensType: 'reflector',
    colorTemp: 3200, weight: 3.5, mountType: 'clamp',
  },
  {
    id: 'par56-mfl', name: 'PAR56 MFL 300W', manufacturer: 'Generic', category: 'par',
    wattage: 300, lumens: 6600, beamAngle: 20, fieldAngle: 40,
    beamShape: 'elliptical', beamRatioWH: 1.8, lensType: 'reflector',
    colorTemp: 3200, weight: 1.5, mountType: 'clamp',
  },

  // ═══════════════════════════════════════════════════════════
  // LED WASH / FLÄCHENLEUCHTEN
  // ═══════════════════════════════════════════════════════════
  {
    id: 'adj-mega-hex-par', name: 'Mega HEX Par', manufacturer: 'ADJ', category: 'wash',
    wattage: 60, lumens: 680, beamAngle: 25, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 1.4, mountType: 'clamp', dmxChannels: 12,
  },
  {
    id: 'chauvet-colordash-h18ip', name: 'COLORdash Par H18IP', manufacturer: 'Chauvet Professional', category: 'wash',
    wattage: 180, lumens: 2500, beamAngle: 22, fieldAngle: 38,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, ipRating: 'IP65', weight: 4.8, mountType: 'clamp', dmxChannels: 14,
  },
  {
    id: 'elation-sixpar-300', name: 'SixPar 300', manufacturer: 'Elation', category: 'wash',
    wattage: 168, lumens: 4200, beamAngle: 22, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 4.2, mountType: 'clamp', dmxChannels: 10,
  },
  {
    id: 'generic-led-par-54x3', name: 'LED PAR 54×3 W RGBW', manufacturer: 'Generic', category: 'wash',
    wattage: 162, lumens: 3200, beamAngle: 25, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 2.8, mountType: 'clamp', dmxChannels: 8,
  },
  {
    id: 'etc-cs-par', name: 'ColorSource PAR', manufacturer: 'ETC', category: 'wash',
    wattage: 125, lumens: 3250, beamAngle: 25, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 92, weight: 3.1, mountType: 'clamp', dmxChannels: 5,
  },

  // ═══════════════════════════════════════════════════════════
  // LED SPOT
  // ═══════════════════════════════════════════════════════════
  {
    id: 'etc-cs-spot', name: 'ColorSource Spot', manufacturer: 'ETC', category: 'spot',
    wattage: 125, lumens: 3250, beamAngle: 25, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [19, 36],
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 92, weight: 5.2, mountType: 'clamp', dmxChannels: 6,
  },

  // ═══════════════════════════════════════════════════════════
  // BEAM-EFFEKTLEUCHTEN
  // ═══════════════════════════════════════════════════════════

  // ═══════════════════════════════════════════════════════════
  // MOVING HEAD WASH
  // ═══════════════════════════════════════════════════════════
  {
    id: 'martin-mac-aura-xb', name: 'MAC Aura XB', manufacturer: 'Martin / Harman', category: 'moving-wash',
    wattage: 270, lumens: 11800, beamAngle: 11, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [11, 58],
    colorTemp: 0, weight: 6.6, mountType: 'yoke', dmxChannels: 23,
  },
  {
    id: 'robe-robin-600-ledwash', name: 'Robin 600 LEDWash', manufacturer: 'Robe', category: 'moving-wash',
    wattage: 270, lumens: 9500, beamAngle: 15, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [15, 60],
    colorTemp: 0, weight: 9.7, mountType: 'yoke', dmxChannels: 18,
  },
  {
    id: 'robe-robin-ledbeam-150', name: 'Robin LEDBeam 150', manufacturer: 'Robe', category: 'moving-wash',
    wattage: 220, lumens: 3550, beamAngle: 3.8, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3.8, 60],
    colorTemp: 0, colorTempRange: [2700, 8000], weight: 5.7, mountType: 'yoke', dmxChannels: 22,
  },
  {
    id: 'chauvet-rogue-r2-wash', name: 'Rogue R2 Wash', manufacturer: 'Chauvet Professional', category: 'moving-wash',
    wattage: 270, lumens: 8200, beamAngle: 12, fieldAngle: 49,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [12, 49],
    colorTemp: 0, weight: 10.1, mountType: 'yoke', dmxChannels: 21,
  },
  {
    id: 'martin-mac-aura-pxl', name: 'MAC Aura PXL', manufacturer: 'Martin / Harman', category: 'moving-wash',
    wattage: 560, lumens: 10500, beamAngle: 6, fieldAngle: 59,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 59],
    colorTemp: 0, colorTempRange: [2000, 10000], weight: 15.6, mountType: 'yoke', dmxChannels: 32,
  },
  {
    id: 'glp-impression-x4', name: 'impression X4', manufacturer: 'GLP', category: 'moving-wash',
    wattage: 350, lumens: 5085, beamAngle: 7, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 50],
    colorTemp: 0, weight: 7.9, mountType: 'yoke',
  },
  {
    id: 'robe-robin-spiider', name: 'Robin Spiider', manufacturer: 'Robe', category: 'moving-wash',
    wattage: 600, lumens: 11000, beamAngle: 4, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 50],
    colorTemp: 0, colorTempRange: [2700, 8000], weight: 13.3, mountType: 'yoke', dmxChannels: 49,
  },

  // ═══════════════════════════════════════════════════════════
  // MOVING HEAD SPOT
  // ═══════════════════════════════════════════════════════════
  {
    id: 'martin-mac-viper-profile', name: 'MAC Viper Profile', manufacturer: 'Martin / Harman', category: 'moving-spot',
    wattage: 1000, lumens: 33000, beamAngle: 10, fieldAngle: 44,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [10, 44],
    colorTemp: 6000, weight: 30.5, mountType: 'yoke', dmxChannels: 26,
  },
  {
    id: 'robe-robin-t1-profile', name: 'Robin T1 Profile', manufacturer: 'Robe', category: 'moving-spot',
    wattage: 468, lumens: 20000, beamAngle: 5, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [5, 50],
    colorTemp: 0, weight: 22, mountType: 'yoke', dmxChannels: 35,
  },
  {
    id: 'chauvet-maverick-mk3-profile', name: 'Maverick MK3 Profile', manufacturer: 'Chauvet Professional', category: 'moving-spot',
    wattage: 820, lumens: 51000, beamAngle: 6, fieldAngle: 46,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 46],
    colorTemp: 7500, weight: 35.3, mountType: 'yoke', dmxChannels: 38,
  },
  // ── Ayrton (LED-Movingheads; Kern-Specs laut Ayrton-Spec-Sheets/Produktdaten 2026-09) ──
  { id: 'ayrton-ghibli', name: 'Ghibli', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 600, lumens: 23000, beamAngle: 7, fieldAngle: 56,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 56],
    colorTemp: 8000, weight: 27, mountType: 'yoke' },
  { id: 'ayrton-diablo', name: 'Diablo', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 300, lumens: 19000, beamAngle: 7, fieldAngle: 53,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 53],
    colorTemp: 7000, weight: 22, mountType: 'yoke' },
  { id: 'ayrton-khamsin', name: 'Khamsin-S', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 1000, lumens: 40000, beamAngle: 7, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 58],
    colorTemp: 6800, weight: 38, mountType: 'yoke' },
  { id: 'ayrton-domino-lt', name: 'Domino LT', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 1000, lumens: 51000, beamAngle: 3.5, fieldAngle: 53,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3.5, 53],
    colorTemp: 8200, weight: 44, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'ayrton-mistral', name: 'Mistral', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 300, lumens: 18000, beamAngle: 7, fieldAngle: 53,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 53],
    colorTemp: 7000, weight: 18.9, mountType: 'yoke' },
  { id: 'ayrton-perseo-profile', name: 'Perseo Profile', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 500, lumens: 27400, beamAngle: 7, fieldAngle: 56,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 56],
    colorTemp: 8000, weight: 33, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'ayrton-karif-lt', name: 'Karif LT', manufacturer: 'Ayrton', category: 'moving-spot',
    wattage: 300, lumens: 14000, beamAngle: 2.8, fieldAngle: 47,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [2.8, 47],
    colorTemp: 7000, weight: 16, mountType: 'yoke' },
  { id: 'ayrton-bora', name: 'Bora-S', manufacturer: 'Ayrton', category: 'moving-wash',
    wattage: 750, lumens: 40000, beamAngle: 8, fieldAngle: 64,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [8, 64],
    colorTemp: 8000, weight: 27, mountType: 'yoke' },
  // ── Weitere Movingheads/Scheinwerfer (Kern-Specs laut Hersteller-Datenblatt 2026-09) ──
  { id: 'etc-s4-led-s3-lustr', name: 'Source Four LED Series 3 Lustr X8', manufacturer: 'ETC', category: 'profile',
    wattage: 340, lumens: 10889, beamAngle: 13, fieldAngle: 26,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 0, cri: 90, weight: 9, mountType: 'clamp' },
  { id: 'etc-colorsource-spot', name: 'ColorSource Spot', manufacturer: 'ETC', category: 'profile',
    wattage: 147, lumens: 6932, beamAngle: 13, fieldAngle: 26,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 0, weight: 6.5, mountType: 'clamp' },
  { id: 'chauvet-maverick-storm-1-wash', name: 'Maverick Storm 1 Wash', manufacturer: 'Chauvet Professional', category: 'moving-wash',
    wattage: 380, lumens: 6000, beamAngle: 11, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [11, 42],
    colorTemp: 0, weight: 26.8, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'elation-proteus-maximus', name: 'Proteus Maximus', manufacturer: 'Elation', category: 'moving-spot',
    wattage: 950, lumens: 50000, beamAngle: 5.5, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [5.5, 55],
    colorTemp: 6500, weight: 53, mountType: 'yoke', ipRating: 'IP65', dmxChannels: 37 },
  { id: 'robe-iforte-ltx', name: 'iForte LTX', manufacturer: 'Robe', category: 'moving-spot',
    wattage: 1000, lumens: 55000, beamAngle: 3.5, fieldAngle: 52,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3.5, 52],
    colorTemp: 6500, weight: 49, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'martin-mac-encore-perf-cld', name: 'MAC Encore Performance CLD', manufacturer: 'Martin / Harman', category: 'moving-spot',
    wattage: 468, lumens: 39400, beamAngle: 12, fieldAngle: 48,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [12, 48],
    colorTemp: 6000, weight: 31, mountType: 'yoke' },
  { id: 'martin-mac-aura-xip', name: 'MAC Aura XIP', manufacturer: 'Martin / Harman', category: 'moving-wash',
    wattage: 300, lumens: 6000, beamAngle: 8, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [8, 60],
    colorTemp: 0, weight: 8.95, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'elation-fuze-max-profile', name: 'Fuze Max Profile', manufacturer: 'Elation', category: 'moving-spot',
    wattage: 800, lumens: 21000, beamAngle: 5.5, fieldAngle: 52,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [5.5, 52],
    colorTemp: 0, weight: 34.6, mountType: 'yoke' },
  { id: 'sgm-p6', name: 'P-6', manufacturer: 'SGM', category: 'flood',
    wattage: 576, lumens: 18297, beamAngle: 21, fieldAngle: 21,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 14.5, mountType: 'yoke', ipRating: 'IP66' },
  { id: 'adj-vizi-beam-12rx', name: 'Vizi Beam 12RX', manufacturer: 'ADJ', category: 'moving-beam',
    wattage: 260, lumens: 9400, beamAngle: 2, fieldAngle: 2,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 7800, weight: 18, mountType: 'yoke' },
  { id: 'astera-ax1-pixeltube', name: 'AX1 PixelTube', manufacturer: 'Astera', category: 'cyc',
    wattage: 28, lumens: 723, beamAngle: 120, fieldAngle: 180,
    beamShape: 'linear', beamRatioWH: 8, lensType: 'fixed',
    colorTemp: 0, weight: 1, mountType: 'clamp', ipRating: 'IP65' },
  { id: 'chauvet-rogue-r2-spot', name: 'Rogue R2 Spot', manufacturer: 'Chauvet Professional', category: 'moving-spot',
    wattage: 300, lumens: 11000, beamAngle: 16.5, fieldAngle: 16.5,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 7000, weight: 21, mountType: 'yoke' },
  { id: 'chauvet-colordash-par-h12x', name: 'COLORdash Par H12X IP', manufacturer: 'Chauvet Professional', category: 'par',
    wattage: 120, lumens: 4532, beamAngle: 22.2, fieldAngle: 22.2,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, colorTempRange: [2800, 10000], weight: 5.35, mountType: 'clamp', ipRating: 'IP65' },
  { id: 'robe-ledbeam-350', name: 'LEDBeam 350', manufacturer: 'Robe', category: 'moving-wash',
    wattage: 480, lumens: 6600, beamAngle: 4, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 50],
    colorTemp: 0, weight: 9.8, mountType: 'yoke' },
  { id: 'elation-kl-panel-xl', name: 'KL Panel XL', manufacturer: 'Elation', category: 'led-panel',
    wattage: 570, lumens: 44000, beamAngle: 110, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1.33, lensType: 'fixed',
    colorTemp: 0, colorTempRange: [2000, 10000], cri: 95, weight: 17.2, mountType: 'yoke' },
  { id: 'adj-focus-spot-6z', name: 'Focus Spot 6Z', manufacturer: 'ADJ', category: 'moving-spot',
    wattage: 300, lumens: 10500, beamAngle: 9, fieldAngle: 28,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [9, 28],
    colorTemp: 7600, weight: 19.4, mountType: 'yoke' },
  { id: 'chauvet-rogue-r1-beamwash', name: 'Rogue R1 BeamWash', manufacturer: 'Chauvet Professional', category: 'moving-wash',
    wattage: 280, lumens: 3941, beamAngle: 3.4, fieldAngle: 67.7,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3.4, 67.7],
    colorTemp: 0, colorTempRange: [2800, 10000], weight: 5.35, mountType: 'yoke' },
  { id: 'fresnel-300w', name: '300 W Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 300, lumens: 6000, beamAngle: 12, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 55],
    colorTemp: 3200, weight: 2.5, mountType: 'clamp' },
  { id: 'fresnel-500w', name: '500 W Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 500, lumens: 11000, beamAngle: 12, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 58],
    colorTemp: 3200, weight: 3.5, mountType: 'clamp' },
  { id: 'fresnel-650w', name: '650 W Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 650, lumens: 14000, beamAngle: 12, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 60],
    colorTemp: 3200, weight: 4.2, mountType: 'clamp' },
  { id: 'fresnel-5kw', name: '5 kW Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 5000, lumens: 110000, beamAngle: 10, fieldAngle: 62,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [10, 62],
    colorTemp: 3200, weight: 22, mountType: 'clamp' },
  { id: 'fresnel-10kw', name: '10 kW Fresnel', manufacturer: 'Generic', category: 'fresnel',
    wattage: 10000, lumens: 260000, beamAngle: 10, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [10, 60],
    colorTemp: 3200, weight: 38, mountType: 'clamp' },
  { id: 'pc-500w', name: '500 W PC', manufacturer: 'Generic', category: 'fresnel',
    wattage: 500, lumens: 11500, beamAngle: 8, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'pc', zoomRange: [8, 50],
    colorTemp: 3200, weight: 3.6, mountType: 'clamp' },
  { id: 'pc-1kw', name: '1 kW PC', manufacturer: 'Generic', category: 'fresnel',
    wattage: 1000, lumens: 23000, beamAngle: 8, fieldAngle: 52,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'pc', zoomRange: [8, 52],
    colorTemp: 3200, weight: 5.8, mountType: 'clamp' },
  { id: 'pc-2kw', name: '2 kW PC', manufacturer: 'Generic', category: 'fresnel',
    wattage: 2000, lumens: 46000, beamAngle: 8, fieldAngle: 54,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'pc', zoomRange: [8, 54],
    colorTemp: 3200, weight: 10.5, mountType: 'clamp' },
  { id: 'par16', name: 'PAR16 (Birdie)', manufacturer: 'Generic', category: 'par',
    wattage: 75, lumens: 900, beamAngle: 10, fieldAngle: 10,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3000, weight: 0.4, mountType: 'clamp' },
  { id: 'par20', name: 'PAR20', manufacturer: 'Generic', category: 'par',
    wattage: 50, lumens: 700, beamAngle: 12, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3000, weight: 0.6, mountType: 'clamp' },
  { id: 'par30', name: 'PAR30', manufacturer: 'Generic', category: 'par',
    wattage: 75, lumens: 1100, beamAngle: 12, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3000, weight: 0.8, mountType: 'clamp' },
  { id: 'par36-pinspot', name: 'PAR36 Pinspot', manufacturer: 'Generic', category: 'par',
    wattage: 30, lumens: 400, beamAngle: 5, fieldAngle: 5,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3000, weight: 0.5, mountType: 'clamp' },
  { id: 'par38', name: 'PAR38', manufacturer: 'Generic', category: 'par',
    wattage: 120, lumens: 1600, beamAngle: 30, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3000, weight: 1.0, mountType: 'clamp' },
  { id: 'profile-750w-26', name: '750 W Profil 26°', manufacturer: 'Generic', category: 'profile',
    wattage: 750, lumens: 10000, beamAngle: 14, fieldAngle: 26,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, weight: 7.5, mountType: 'clamp' },
  { id: 'profile-750w-36', name: '750 W Profil 36°', manufacturer: 'Generic', category: 'profile',
    wattage: 750, lumens: 9500, beamAngle: 20, fieldAngle: 36,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, weight: 7.5, mountType: 'clamp' },
  { id: 'profile-1kw-19', name: '1 kW Profil 19°', manufacturer: 'Generic', category: 'profile',
    wattage: 1000, lumens: 14000, beamAngle: 10, fieldAngle: 19,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, weight: 8.5, mountType: 'clamp' },
  { id: 'profile-1kw-zoom', name: '1 kW Zoom-Profil 15-40°', manufacturer: 'Generic', category: 'profile',
    wattage: 1000, lumens: 13000, beamAngle: 15, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [15, 40],
    colorTemp: 3200, weight: 9.5, mountType: 'clamp' },
  { id: 'profile-2kw', name: '2 kW Profil', manufacturer: 'Generic', category: 'profile',
    wattage: 2000, lumens: 30000, beamAngle: 12, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, weight: 13, mountType: 'clamp' },
  { id: 'cyc-1kw-asym', name: '1 kW Cyc (asymmetrisch)', manufacturer: 'Generic', category: 'cyc',
    wattage: 1000, lumens: 22000, beamAngle: 70, fieldAngle: 110,
    beamShape: 'linear', beamRatioWH: 3, lensType: 'reflector',
    colorTemp: 3200, weight: 5.5, mountType: 'clamp' },
  { id: 'flood-500w', name: '500 W Fluter', manufacturer: 'Generic', category: 'flood',
    wattage: 500, lumens: 10500, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 2.2, mountType: 'clamp' },
  { id: 'flood-1kw', name: '1 kW Fluter', manufacturer: 'Generic', category: 'flood',
    wattage: 1000, lumens: 21000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 3.4, mountType: 'clamp' },
  { id: 'flood-1kw-4cell-cyc', name: '4-Zellen Cyc 1 kW', manufacturer: 'Generic', category: 'cyc',
    wattage: 4000, lumens: 88000, beamAngle: 70, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 4, lensType: 'reflector',
    colorTemp: 3200, weight: 14, mountType: 'clamp' },
  { id: 'blinder-dwe-4', name: '4-Lite Blinder (DWE)', manufacturer: 'Generic', category: 'blinder',
    wattage: 2600, lumens: 52000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 4.5, mountType: 'clamp' },
  { id: 'blinder-dwe-8', name: '8-Lite Blinder (DWE)', manufacturer: 'Generic', category: 'blinder',
    wattage: 5200, lumens: 104000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 7.8, mountType: 'clamp' },
  { id: 'blinder-acl', name: 'ACL 4-Bar', manufacturer: 'Generic', category: 'blinder',
    wattage: 1200, lumens: 18000, beamAngle: 8, fieldAngle: 8,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 3.2, mountType: 'clamp' },
  { id: 'followspot-575', name: '575 W Verfolger (HMI)', manufacturer: 'Generic', category: 'followspot',
    wattage: 575, lumens: 42000, beamAngle: 5, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [5, 12],
    colorTemp: 6000, weight: 18, mountType: 'yoke' },
  { id: 'followspot-1200', name: '1200 W Verfolger (HMI)', manufacturer: 'Generic', category: 'followspot',
    wattage: 1200, lumens: 85000, beamAngle: 4, fieldAngle: 10,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 10],
    colorTemp: 6000, weight: 28, mountType: 'yoke' },
  { id: 'followspot-2500', name: '2500 W Verfolger (HMI)', manufacturer: 'Generic', category: 'followspot',
    wattage: 2500, lumens: 180000, beamAngle: 3, fieldAngle: 9,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3, 9],
    colorTemp: 6000, weight: 45, mountType: 'yoke' },
  { id: 'led-par-rgbw-18', name: 'LED PAR 18×10 W RGBW', manufacturer: 'Generic', category: 'par',
    wattage: 180, lumens: 3600, beamAngle: 15, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 3.2, mountType: 'clamp' },
  { id: 'led-par-rgbwa-uv', name: 'LED PAR 12×12 W RGBWA+UV', manufacturer: 'Generic', category: 'par',
    wattage: 144, lumens: 3200, beamAngle: 20, fieldAngle: 25,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 2.8, mountType: 'clamp' },
  { id: 'led-par-zoom', name: 'LED PAR Zoom RGBW 19×15 W', manufacturer: 'Generic', category: 'par',
    wattage: 285, lumens: 5500, beamAngle: 7, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 58],
    colorTemp: 0, weight: 4.5, mountType: 'clamp' },
  { id: 'led-batten-1m', name: 'LED Batten 1 m RGBW', manufacturer: 'Generic', category: 'cyc',
    wattage: 150, lumens: 4200, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 8, lensType: 'fixed',
    colorTemp: 0, weight: 3.5, mountType: 'clamp' },
  { id: 'led-strip-cob', name: 'LED COB Strip Warm/Cool', manufacturer: 'Generic', category: 'cyc',
    wattage: 200, lumens: 6000, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 10, lensType: 'fixed',
    colorTemp: 0, weight: 240, mountType: 'clamp', colorTempRange: [2700, 6500] },
  { id: 'led-panel-bicolor-1x1', name: 'LED Panel 1×1 Bicolor', manufacturer: 'Generic', category: 'led-panel',
    wattage: 100, lumens: 5000, beamAngle: 50, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 2.5, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'led-blinder-2x100', name: 'LED Blinder 2×100 W Warmweiß', manufacturer: 'Generic', category: 'blinder',
    wattage: 200, lumens: 7000, beamAngle: 50, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 2700, weight: 3.0, mountType: 'clamp' },
  { id: 'led-strobe-1000', name: 'LED Strobe 1000 W', manufacturer: 'Generic', category: 'blinder',
    wattage: 1000, lumens: 26000, beamAngle: 90, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 6500, weight: 6.5, mountType: 'yoke' },
  { id: 'led-fresnel-100-bi', name: 'LED Fresnel 100 W Bicolor', manufacturer: 'Generic', category: 'fresnel',
    wattage: 100, lumens: 4200, beamAngle: 12, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 55],
    colorTemp: 0, weight: 3.5, mountType: 'clamp', colorTempRange: [2800, 6500], cri: 95 },
  { id: 'led-fresnel-200-bi', name: 'LED Fresnel 200 W Bicolor', manufacturer: 'Generic', category: 'fresnel',
    wattage: 200, lumens: 8500, beamAngle: 10, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [10, 58],
    colorTemp: 0, weight: 5.5, mountType: 'clamp', colorTempRange: [2800, 6500], cri: 95 },
  { id: 'led-fresnel-300-rgbw', name: 'LED Fresnel 300 W RGBW', manufacturer: 'Generic', category: 'fresnel',
    wattage: 300, lumens: 9000, beamAngle: 12, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 60],
    colorTemp: 0, weight: 6.5, mountType: 'clamp' },
  { id: 'led-pc-200-bi', name: 'LED PC 200 W Bicolor', manufacturer: 'Generic', category: 'fresnel',
    wattage: 200, lumens: 8000, beamAngle: 8, fieldAngle: 52,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'pc', zoomRange: [8, 52],
    colorTemp: 0, weight: 5.2, mountType: 'clamp', colorTempRange: [2800, 6500] },
  { id: 'led-profile-150-bi', name: 'LED Profil 150 W Bicolor', manufacturer: 'Generic', category: 'profile',
    wattage: 150, lumens: 6000, beamAngle: 14, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 0, weight: 7.0, mountType: 'clamp', colorTempRange: [2800, 6500], cri: 92 },
  { id: 'led-profile-300-rgba', name: 'LED Profil 300 W RGBAL', manufacturer: 'Generic', category: 'profile',
    wattage: 300, lumens: 9500, beamAngle: 10, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [10, 40],
    colorTemp: 0, weight: 9.0, mountType: 'clamp' },
  { id: 'led-cyc-rgbw-4cell', name: 'LED Cyc RGBW 4-Zellen', manufacturer: 'Generic', category: 'cyc',
    wattage: 400, lumens: 12000, beamAngle: 70, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 4, lensType: 'fixed',
    colorTemp: 0, weight: 8.5, mountType: 'clamp' },
  { id: 'led-tube-05', name: 'LED Pixel-Tube 0.5 m', manufacturer: 'Generic', category: 'cyc',
    wattage: 15, lumens: 360, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 4, lensType: 'fixed',
    colorTemp: 0, weight: 0.6, mountType: 'clamp' },
  { id: 'led-tube-2m', name: 'LED Pixel-Tube 2 m', manufacturer: 'Generic', category: 'cyc',
    wattage: 60, lumens: 1450, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 16, lensType: 'fixed',
    colorTemp: 0, weight: 1.8, mountType: 'clamp' },
  { id: 'led-strip-rgb-1m', name: 'LED Strip RGB 1 m', manufacturer: 'Generic', category: 'cyc',
    wattage: 40, lumens: 1200, beamAngle: 120, fieldAngle: 140,
    beamShape: 'linear', beamRatioWH: 20, lensType: 'fixed',
    colorTemp: 0, weight: 0.8, mountType: 'clamp' },
  { id: 'led-strip-warm-2m', name: 'LED Strip Warmweiß 2 m', manufacturer: 'Generic', category: 'cyc',
    wattage: 80, lumens: 2600, beamAngle: 120, fieldAngle: 140,
    beamShape: 'linear', beamRatioWH: 20, lensType: 'fixed',
    colorTemp: 2700, weight: 1.4, mountType: 'clamp' },
  { id: 'mh-spot-150', name: 'Moving Head Spot 150 W', manufacturer: 'Generic', category: 'moving-spot',
    wattage: 150, lumens: 6000, beamAngle: 12, fieldAngle: 28,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [12, 28],
    colorTemp: 7000, weight: 12, mountType: 'yoke' },
  { id: 'mh-spot-250', name: 'Moving Head Spot 250 W', manufacturer: 'Generic', category: 'moving-spot',
    wattage: 250, lumens: 11000, beamAngle: 10, fieldAngle: 32,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [10, 32],
    colorTemp: 7000, weight: 16, mountType: 'yoke' },
  { id: 'mh-spot-350', name: 'Moving Head Spot 350 W', manufacturer: 'Generic', category: 'moving-spot',
    wattage: 350, lumens: 16000, beamAngle: 9, fieldAngle: 38,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [9, 38],
    colorTemp: 7500, weight: 20, mountType: 'yoke' },
  { id: 'mh-spot-440', name: 'Moving Head Spot 440 W', manufacturer: 'Generic', category: 'moving-spot',
    wattage: 440, lumens: 20000, beamAngle: 8, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [8, 42],
    colorTemp: 7500, weight: 24, mountType: 'yoke' },
  { id: 'mh-wash-7x15', name: 'Moving Head Wash 7×15 W RGBW', manufacturer: 'Generic', category: 'moving-wash',
    wattage: 105, lumens: 3200, beamAngle: 8, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [8, 55],
    colorTemp: 0, weight: 9, mountType: 'yoke' },
  { id: 'mh-wash-19x15', name: 'Moving Head Wash 19×15 W RGBW', manufacturer: 'Generic', category: 'moving-wash',
    wattage: 285, lumens: 6800, beamAngle: 6, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 60],
    colorTemp: 0, weight: 14, mountType: 'yoke' },
  { id: 'mh-wash-37x15', name: 'Moving Head Wash 37×15 W RGBW', manufacturer: 'Generic', category: 'moving-wash',
    wattage: 555, lumens: 12500, beamAngle: 5, fieldAngle: 62,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [5, 62],
    colorTemp: 0, weight: 22, mountType: 'yoke' },
  { id: 'mh-beam-5r', name: 'Moving Head Beam 5R (200 W)', manufacturer: 'Generic', category: 'moving-beam',
    wattage: 200, lumens: 8000, beamAngle: 3, fieldAngle: 3,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 8000, weight: 15, mountType: 'yoke' },
  { id: 'mh-beam-7r', name: 'Moving Head Beam 7R (230 W)', manufacturer: 'Generic', category: 'moving-beam',
    wattage: 230, lumens: 10000, beamAngle: 3, fieldAngle: 3,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 8000, weight: 18, mountType: 'yoke' },
  { id: 'mh-beam-9r', name: 'Moving Head Beam 9R (260 W)', manufacturer: 'Generic', category: 'moving-beam',
    wattage: 260, lumens: 12000, beamAngle: 2, fieldAngle: 4,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 8000, weight: 20, mountType: 'yoke' },
  { id: 'mh-bsw-19x40', name: 'Moving Head BSW 19×40 W RGBW', manufacturer: 'Generic', category: 'moving-beam',
    wattage: 760, lumens: 15000, beamAngle: 4, fieldAngle: 60,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 60],
    colorTemp: 0, weight: 26, mountType: 'yoke' },
  { id: 'led-blinder-3x100', name: 'LED Blinder 3×100 W WW', manufacturer: 'Generic', category: 'blinder',
    wattage: 300, lumens: 10500, beamAngle: 50, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 2700, weight: 4.2, mountType: 'clamp' },
  { id: 'led-strobe-500', name: 'LED Strobe 500 W RGB', manufacturer: 'Generic', category: 'blinder',
    wattage: 500, lumens: 14000, beamAngle: 90, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 6500, weight: 4.8, mountType: 'yoke' },
  { id: 'led-matrix-25', name: 'LED Matrix 5×5 RGB', manufacturer: 'Generic', category: 'blinder',
    wattage: 250, lumens: 7000, beamAngle: 40, fieldAngle: 70,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 5.0, mountType: 'yoke' },
  { id: 'led-wash-bar-8', name: 'LED Wash-Bar 8×10 W RGBW', manufacturer: 'Generic', category: 'wash',
    wattage: 80, lumens: 2400, beamAngle: 15, fieldAngle: 40,
    beamShape: 'rectangular', beamRatioWH: 4, lensType: 'fixed',
    colorTemp: 0, weight: 2.4, mountType: 'clamp' },
  { id: 'led-wash-bar-18', name: 'LED Wash-Bar 18×10 W RGBW', manufacturer: 'Generic', category: 'wash',
    wattage: 180, lumens: 4600, beamAngle: 15, fieldAngle: 40,
    beamShape: 'rectangular', beamRatioWH: 6, lensType: 'fixed',
    colorTemp: 0, weight: 4.0, mountType: 'clamp' },
  { id: 'uv-cannon-led', name: 'UV-Cannon LED 200 W', manufacturer: 'Generic', category: 'flood',
    wattage: 200, lumens: 0, beamAngle: 20, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 4.5, mountType: 'yoke' },
  { id: 'followspot-led-300', name: 'LED-Verfolger 300 W', manufacturer: 'Generic', category: 'followspot',
    wattage: 300, lumens: 12000, beamAngle: 4, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 12],
    colorTemp: 6000, weight: 16, mountType: 'yoke' },
  { id: 'led-par-64-rgb', name: 'LED PAR 64 RGB 3 W×183', manufacturer: 'Generic', category: 'par',
    wattage: 180, lumens: 3000, beamAngle: 25, fieldAngle: 25,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 3.0, mountType: 'clamp' },
  { id: 'led-flatpar-rgbw', name: 'LED Flat PAR 7×10 W RGBW', manufacturer: 'Generic', category: 'par',
    wattage: 70, lumens: 1900, beamAngle: 25, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 1.6, mountType: 'clamp' },
  { id: 'led-flood-100-rgbw', name: 'LED Fluter 100 W RGBW IP65', manufacturer: 'Generic', category: 'flood',
    wattage: 100, lumens: 3600, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 3.2, mountType: 'clamp', ipRating: 'IP65' },
  { id: 'led-groundrow-rgb', name: 'LED Ground-Row RGB 6-Zellen', manufacturer: 'Generic', category: 'cyc',
    wattage: 300, lumens: 9000, beamAngle: 70, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 6, lensType: 'fixed',
    colorTemp: 0, weight: 9.5, mountType: 'clamp' },
  { id: 'mh-wash-zoom-ip', name: 'Moving Head Wash 19×40 W IP65', manufacturer: 'Generic', category: 'moving-wash',
    wattage: 760, lumens: 13500, beamAngle: 4, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 55],
    colorTemp: 0, weight: 24, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'mh-profile-580', name: 'Moving Head Profil 580 W', manufacturer: 'Generic', category: 'moving-spot',
    wattage: 580, lumens: 22000, beamAngle: 7, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 50],
    colorTemp: 7000, weight: 32, mountType: 'yoke' },
  { id: 'mh-hybrid-380', name: 'Moving Head Hybrid 380 W', manufacturer: 'Generic', category: 'moving-beam',
    wattage: 380, lumens: 15000, beamAngle: 3, fieldAngle: 40,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3, 40],
    colorTemp: 7500, weight: 23, mountType: 'yoke' },
  { id: 'fluoro-4x4', name: 'Leuchtstoff 4×4 ft (4-Rohr)', manufacturer: 'Generic', category: 'led-panel',
    wattage: 216, lumens: 7200, beamAngle: 60, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1.3, lensType: 'fixed',
    colorTemp: 0, weight: 9, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'fluoro-2x4', name: 'Leuchtstoff 2×4 ft', manufacturer: 'Generic', category: 'led-panel',
    wattage: 110, lumens: 3800, beamAngle: 60, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 2, lensType: 'fixed',
    colorTemp: 0, weight: 5, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'fluoro-tube-4ft', name: 'Leuchtstoffröhre 4 ft einzeln', manufacturer: 'Generic', category: 'cyc',
    wattage: 55, lumens: 2000, beamAngle: 120, fieldAngle: 140,
    beamShape: 'linear', beamRatioWH: 10, lensType: 'fixed',
    colorTemp: 0, weight: 1.2, mountType: 'clamp' },
  { id: 'led-mat-2x1', name: 'LED-Matte 2×1', manufacturer: 'Generic', category: 'led-panel',
    wattage: 120, lumens: 5000, beamAngle: 60, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 2, lensType: 'fixed',
    colorTemp: 0, weight: 3.5, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'led-mat-4x4', name: 'LED-Matte 4×4', manufacturer: 'Generic', category: 'led-panel',
    wattage: 480, lumens: 20000, beamAngle: 55, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 9.5, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'led-softpanel-1x1-rgbw', name: 'LED Softpanel 1×1 RGBW', manufacturer: 'Generic', category: 'led-panel',
    wattage: 150, lumens: 5500, beamAngle: 50, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 3.2, mountType: 'yoke' },
  { id: 'led-skypanel-s60', name: 'LED Softpanel S60 RGBW', manufacturer: 'Generic', category: 'led-panel',
    wattage: 450, lumens: 32000, beamAngle: 45, fieldAngle: 105,
    beamShape: 'rectangular', beamRatioWH: 1.4, lensType: 'fixed',
    colorTemp: 0, weight: 13, mountType: 'yoke' },
  { id: 'led-skypanel-s120', name: 'LED Softpanel S120 RGBW', manufacturer: 'Generic', category: 'led-panel',
    wattage: 850, lumens: 60000, beamAngle: 45, fieldAngle: 105,
    beamShape: 'rectangular', beamRatioWH: 2.4, lensType: 'fixed',
    colorTemp: 0, weight: 22, mountType: 'yoke' },
  { id: 'led-litemat-4', name: 'LED Bi-Color Mat 4', manufacturer: 'Generic', category: 'led-panel',
    wattage: 450, lumens: 18000, beamAngle: 55, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 2, lensType: 'fixed',
    colorTemp: 0, weight: 8, mountType: 'yoke', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'cob-120d', name: 'COB 120 W Tageslicht', manufacturer: 'Generic', category: 'spot',
    wattage: 120, lumens: 4500, beamAngle: 15, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 45],
    colorTemp: 5600, weight: 2.0, mountType: 'clamp' },
  { id: 'cob-300d', name: 'COB 300 W Tageslicht', manufacturer: 'Generic', category: 'spot',
    wattage: 300, lumens: 13500, beamAngle: 15, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 45],
    colorTemp: 5600, weight: 3.5, mountType: 'clamp' },
  { id: 'cob-600d', name: 'COB 600 W Tageslicht', manufacturer: 'Generic', category: 'spot',
    wattage: 600, lumens: 27000, beamAngle: 15, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 45],
    colorTemp: 5600, weight: 5.5, mountType: 'clamp' },
  { id: 'cob-1200d', name: 'COB 1200 W Tageslicht', manufacturer: 'Generic', category: 'spot',
    wattage: 1200, lumens: 55000, beamAngle: 15, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 45],
    colorTemp: 5600, weight: 9.5, mountType: 'yoke' },
  { id: 'cob-300x-bi', name: 'COB 300 W Bicolor', manufacturer: 'Generic', category: 'spot',
    wattage: 300, lumens: 12000, beamAngle: 15, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [15, 45],
    colorTemp: 0, weight: 3.6, mountType: 'clamp', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'space-light-6k', name: 'Space Light 6 kW', manufacturer: 'Generic', category: 'flood',
    wattage: 6000, lumens: 140000, beamAngle: 90, fieldAngle: 120,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 12, mountType: 'clamp' },
  { id: 'space-light-led', name: 'LED Space Light', manufacturer: 'Generic', category: 'flood',
    wattage: 600, lumens: 22000, beamAngle: 90, fieldAngle: 120,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 6, mountType: 'clamp', colorTempRange: [3200, 5600], cri: 95 },
  { id: 'book-light', name: 'Book Light (Bounce+Diffusion)', manufacturer: 'Generic', category: 'flood',
    wattage: 300, lumens: 7000, beamAngle: 80, fieldAngle: 110,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 4, mountType: 'yoke' },
  { id: 'china-ball-100', name: 'China Ball 100 W', manufacturer: 'Generic', category: 'flood',
    wattage: 100, lumens: 1600, beamAngle: 180, fieldAngle: 300,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 3200, weight: 0.5, mountType: 'clamp' },
  { id: 'lantern-led', name: 'LED Lantern 200 W', manufacturer: 'Generic', category: 'flood',
    wattage: 200, lumens: 6000, beamAngle: 180, fieldAngle: 320,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 1.5, mountType: 'clamp' },
  { id: 'hmi-par-575', name: 'HMI PAR 575 W', manufacturer: 'Generic', category: 'spot',
    wattage: 575, lumens: 49000, beamAngle: 7, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector', zoomRange: [7, 55],
    colorTemp: 6000, weight: 7, mountType: 'yoke' },
  { id: 'hmi-par-1200', name: 'HMI PAR 1200 W', manufacturer: 'Generic', category: 'spot',
    wattage: 1200, lumens: 110000, beamAngle: 7, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector', zoomRange: [7, 55],
    colorTemp: 6000, weight: 11, mountType: 'yoke' },
  { id: 'hmi-par-2500', name: 'HMI PAR 2500 W', manufacturer: 'Generic', category: 'spot',
    wattage: 2500, lumens: 240000, beamAngle: 7, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector', zoomRange: [7, 55],
    colorTemp: 6000, weight: 18, mountType: 'yoke' },
  { id: 'hmi-fresnel-1200', name: 'HMI Fresnel 1200 W', manufacturer: 'Generic', category: 'fresnel',
    wattage: 1200, lumens: 95000, beamAngle: 10, fieldAngle: 55,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [10, 55],
    colorTemp: 6000, weight: 14, mountType: 'yoke' },
  { id: 'hmi-fresnel-4000', name: 'HMI Fresnel 4 kW', manufacturer: 'Generic', category: 'fresnel',
    wattage: 4000, lumens: 320000, beamAngle: 8, fieldAngle: 58,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [8, 58],
    colorTemp: 6000, weight: 30, mountType: 'yoke' },
  { id: 'gobo-projector-led', name: 'LED Gobo-Projektor 100 W', manufacturer: 'Generic', category: 'profile',
    wattage: 100, lumens: 3500, beamAngle: 12, fieldAngle: 26,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 3200, weight: 4.5, mountType: 'clamp' },
  { id: 'pixel-bar-16', name: 'Pixel-Bar 16×3 W RGB', manufacturer: 'Generic', category: 'wash',
    wattage: 48, lumens: 1400, beamAngle: 15, fieldAngle: 30,
    beamShape: 'rectangular', beamRatioWH: 8, lensType: 'fixed',
    colorTemp: 0, weight: 2.2, mountType: 'clamp' },
  { id: 'pixel-dot-cluster', name: 'Pixel-Dot Cluster 25×', manufacturer: 'Generic', category: 'blinder',
    wattage: 75, lumens: 2000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, weight: 3.0, mountType: 'yoke' },
  { id: 'led-bar-pixel-1m', name: 'LED Pixel-Bar 1 m 40×', manufacturer: 'Generic', category: 'cyc',
    wattage: 120, lumens: 3200, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 16, lensType: 'fixed',
    colorTemp: 0, weight: 2.5, mountType: 'clamp' },
  { id: 'birdie-led', name: 'LED Birdie 10 W', manufacturer: 'Generic', category: 'par',
    wattage: 10, lumens: 320, beamAngle: 12, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 3000, weight: 0.3, mountType: 'clamp' },
  { id: 'sunstrip-10', name: 'Sunstrip 10×,warmweiß', manufacturer: 'Generic', category: 'blinder',
    wattage: 330, lumens: 9000, beamAngle: 20, fieldAngle: 30,
    beamShape: 'linear', beamRatioWH: 10, lensType: 'fixed',
    colorTemp: 2700, weight: 3.2, mountType: 'clamp' },
  { id: 'molefay-9', name: '9-Lite Molefay (DWE)', manufacturer: 'Generic', category: 'blinder',
    wattage: 5850, lumens: 110000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 8.5, mountType: 'clamp' },
  { id: 'molefay-2', name: '2-Lite Molefay', manufacturer: 'Generic', category: 'blinder',
    wattage: 1300, lumens: 26000, beamAngle: 60, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 3200, weight: 3.0, mountType: 'clamp' },
  { id: 'cyc-led-rgbaw', name: 'LED Cyc RGBAW 200 W', manufacturer: 'Generic', category: 'cyc',
    wattage: 200, lumens: 6500, beamAngle: 70, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 3, lensType: 'fixed',
    colorTemp: 0, weight: 5.5, mountType: 'clamp' },
  { id: 'led-tube-rgb-1m', name: 'LED RGB-Tube 1 m', manufacturer: 'Generic', category: 'cyc',
    wattage: 30, lumens: 720, beamAngle: 110, fieldAngle: 120,
    beamShape: 'linear', beamRatioWH: 8, lensType: 'fixed',
    colorTemp: 0, weight: 1.0, mountType: 'clamp' },
  // ── Cameo (Adam Hall; Kern-Specs laut Cameo-Produktdaten 2026-09; * = Herstellerklasse-Schaetzwert) ──
  { id: 'cameo-opus-s5', name: 'OPUS S5', manufacturer: 'Cameo', category: 'moving-spot',
    wattage: 380, lumens: 17500, beamAngle: 6, fieldAngle: 46,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 46],
    colorTemp: 6700, weight: 24, mountType: 'yoke' },
  { id: 'cameo-opus-h5', name: 'OPUS H5', manufacturer: 'Cameo', category: 'moving-beam',
    wattage: 470, lumens: 18000, beamAngle: 2, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [2, 42],
    colorTemp: 7500, weight: 27, mountType: 'yoke' },
  { id: 'cameo-otos-h5', name: 'OTOS H5', manufacturer: 'Cameo', category: 'moving-beam',
    wattage: 480, lumens: 19000, beamAngle: 2, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [2, 42],
    colorTemp: 7500, weight: 33, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'cameo-otos-sp6', name: 'OTOS SP6', manufacturer: 'Cameo', category: 'moving-spot',
    wattage: 600, lumens: 26000, beamAngle: 6, fieldAngle: 46,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 46],
    colorTemp: 7000, weight: 34, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'cameo-evos-s3', name: 'EVOS S3', manufacturer: 'Cameo', category: 'moving-spot',
    wattage: 350, lumens: 12000, beamAngle: 10, fieldAngle: 38,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [10, 38],
    colorTemp: 6500, weight: 20, mountType: 'yoke' },
  { id: 'cameo-evos-w7', name: 'EVOS W7', manufacturer: 'Cameo', category: 'moving-wash',
    wattage: 760, lumens: 12500, beamAngle: 7, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 50],
    colorTemp: 0, colorTempRange: [2700, 8000], weight: 23.5, mountType: 'yoke' },
  { id: 'cameo-otos-b5', name: 'OTOS B5', manufacturer: 'Cameo', category: 'moving-beam',
    wattage: 480, lumens: 19000, beamAngle: 2, fieldAngle: 24,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [2, 24],
    colorTemp: 7500, weight: 33, mountType: 'yoke', ipRating: 'IP65' },
  { id: 'cameo-movo-beam-z100', name: 'MOVO BEAM Z100', manufacturer: 'Cameo', category: 'moving-beam',
    wattage: 100, lumens: 3000, beamAngle: 4, fieldAngle: 30,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 30],
    colorTemp: 8000, weight: 9.5, mountType: 'yoke' },

  // ═══════════════════════════════════════════════════════════
  // MOVING HEAD BEAM / BSW (Beam Spot Wash Hybrid)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'robe-robin-megapointe', name: 'Robin MegaPointe', manufacturer: 'Robe', category: 'moving-beam',
    wattage: 470, lumens: 23000, beamAngle: 3, fieldAngle: 45,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [3, 45],
    colorTemp: 6500, weight: 21.5, mountType: 'yoke', dmxChannels: 30,
  },
  {
    id: 'robe-robin-pointe', name: 'Robin Pointe', manufacturer: 'Robe', category: 'moving-beam',
    wattage: 470, lumens: 9870, beamAngle: 2.5, fieldAngle: 20,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [2.5, 20],
    colorTemp: 7000, cri: 75, weight: 15, mountType: 'yoke', dmxChannels: 30,
  },
  {
    id: 'claypaky-mythos2', name: 'Mythos 2', manufacturer: 'Clay Paky', category: 'moving-beam',
    wattage: 470, lumens: 23000, beamAngle: 4, fieldAngle: 50,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [4, 50],
    colorTemp: 6000, weight: 26, mountType: 'yoke', dmxChannels: 26,
  },
  {
    id: 'claypaky-sharpy', name: 'Sharpy', manufacturer: 'Clay Paky', category: 'moving-beam',
    wattage: 189, lumens: 7950, beamAngle: 3.8, fieldAngle: 3.8,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 8000, weight: 19, mountType: 'yoke', dmxChannels: 16,
  },

  // ═══════════════════════════════════════════════════════════
  // BLINDER / STROBE
  // ═══════════════════════════════════════════════════════════
  {
    id: 'molefay-4lite', name: 'Molefay 4-Lite', manufacturer: 'Mole-Richardson', category: 'blinder',
    wattage: 2600, lumens: 65000, beamAngle: 90, fieldAngle: 120,
    beamShape: 'rectangular', beamRatioWH: 2.0, lensType: 'reflector',
    colorTemp: 3200, weight: 6.8, mountType: 'baby',
  },
  {
    id: 'martin-atomic-3000', name: 'Atomic 3000 DMX', manufacturer: 'Martin / Harman', category: 'blinder',
    wattage: 3000, lumens: 200000, beamAngle: 120, fieldAngle: 160,
    beamShape: 'rectangular', beamRatioWH: 1.5, lensType: 'reflector',
    colorTemp: 5600, weight: 7.2, mountType: 'clamp', dmxChannels: 4,
  },

  // ═══════════════════════════════════════════════════════════
  // CYC / HORIZONTLEUCHTEN
  // ═══════════════════════════════════════════════════════════
  {
    id: 'etc-cs-cyc', name: 'ColorSource CYC', manufacturer: 'ETC', category: 'cyc',
    wattage: 165, lumens: 5000, beamAngle: 115, fieldAngle: 145,
    beamShape: 'linear', beamRatioWH: 4.0, lensType: 'fixed',
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 92, weight: 6.8, mountType: 'clamp', dmxChannels: 6,
  },
  {
    id: 'arri-cyc-1250', name: 'CYC 1250', manufacturer: 'ARRI', category: 'cyc',
    wattage: 1250, lumens: 28000, beamAngle: 130, fieldAngle: 160,
    beamShape: 'linear', beamRatioWH: 5.0, lensType: 'reflector',
    colorTemp: 3200, weight: 7.4, mountType: 'clamp',
  },

  // ═══════════════════════════════════════════════════════════
  // FLUTER / FLOODLIGHT
  // ═══════════════════════════════════════════════════════════
  {
    id: 'etc-desire-d22', name: 'Desire D22', manufacturer: 'ETC', category: 'flood',
    wattage: 50, lumens: 1800, beamAngle: 24, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, cri: 95, weight: 2.9, mountType: 'clamp', dmxChannels: 5,
  },
  {
    id: 'etc-desire-d40', name: 'Desire D40', manufacturer: 'ETC', category: 'flood',
    wattage: 100, lumens: 3600, beamAngle: 24, fieldAngle: 42,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, cri: 95, weight: 4.1, mountType: 'clamp', dmxChannels: 5,
  },
  {
    id: 'philips-colorblast-12', name: 'ColorBlast 12', manufacturer: 'Philips / ColorKinetics', category: 'flood',
    wattage: 48, lumens: 1200, beamAngle: 10, fieldAngle: 30,
    beamShape: 'rectangular', beamRatioWH: 1.3, lensType: 'fixed',
    colorTemp: 0, weight: 3.0, mountType: 'clamp',
  },

  // ═══════════════════════════════════════════════════════════
  // VERFOLGER (Followspot)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'robert-juliat-cyrano', name: 'Cyrano 2500W', manufacturer: 'Robert Juliat', category: 'followspot',
    wattage: 2500, lumens: 68000, beamAngle: 7, fieldAngle: 14,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 14],
    colorTemp: 6000, weight: 23, mountType: 'yoke',
  },

  // ═══════════════════════════════════════════════════════════
  // LED PANELS / FLÄCHENLEUCHTEN MIT BOWENS-MOUNT
  // Professionelle LED-Scheinwerfer für Film & Bühne
  // ═══════════════════════════════════════════════════════════
  {
    id: 'aputure-ls-600x-pro', name: 'LS 600x Pro', manufacturer: 'Aputure', category: 'led-panel',
    wattage: 600, lumens: 36000, beamAngle: 55, fieldAngle: 80,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 96, tlci: 98,
    weight: 5.16, mountType: 'bowens',
    // Measured bare (with Hyper Reflector) at 5600K: 16,060 lux @ 1m
    photometric: { lux: 16060, distance: 1, beamAngle: 55, colorTemp: 5600 },
    powerConnector: 'Neutrik TRUE1', dmxChannels: 8,
    compatibleAttachments: [
      attachmentLibrary.find((a) => a.id === 'aputure-f10-fresnel')!,
      attachmentLibrary.find((a) => a.id === 'aputure-hyper-reflector')!,
      attachmentLibrary.find((a) => a.id === 'aputure-light-dome-iii')!,
      attachmentLibrary.find((a) => a.id === 'aputure-lantern-90')!,
      attachmentLibrary.find((a) => a.id === 'aputure-spotlight-mount')!,
      attachmentLibrary.find((a) => a.id === 'generic-barndoors-bowens')!,
      attachmentLibrary.find((a) => a.id === 'generic-snoot-bowens')!,
    ],
  },
  {
    id: 'aputure-ls-300x-ii', name: 'LS 300x II', manufacturer: 'Aputure', category: 'led-panel',
    wattage: 350, lumens: 18000, beamAngle: 55, fieldAngle: 80,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'reflector',
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 96, tlci: 97,
    weight: 3.45, mountType: 'bowens',
    photometric: { lux: 8050, distance: 1, beamAngle: 55, colorTemp: 5600 },
    powerConnector: 'Neutrik TRUE1', dmxChannels: 4,
    compatibleAttachments: [
      attachmentLibrary.find((a) => a.id === 'aputure-f10-fresnel')!,
      attachmentLibrary.find((a) => a.id === 'aputure-hyper-reflector')!,
      attachmentLibrary.find((a) => a.id === 'aputure-light-dome-iii')!,
      attachmentLibrary.find((a) => a.id === 'aputure-lantern-90')!,
      attachmentLibrary.find((a) => a.id === 'aputure-spotlight-mount')!,
      attachmentLibrary.find((a) => a.id === 'generic-barndoors-bowens')!,
      attachmentLibrary.find((a) => a.id === 'generic-snoot-bowens')!,
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // ELATION – aktuelle LED-Serie (KL / Fuze)
  // Werte aus den Hersteller-Datenblättern (Stand 2024/25);
  // Illuminance teils auf 1 m Referenzabstand normiert / geschätzt.
  // ═══════════════════════════════════════════════════════════
  {
    // Values from the Elation KL Fresnel 8 FC photometric test report (3/29/2021).
    // Zoom (beam 50%): 10.4° (spot) … 50.8° (flood); field 10%: 20.6°…66.1°;
    // cutoff 2.5%: 29.2°…88.2°. Peak 158,552 cd @ spot, 25,590 cd @ flood.
    // Max output 16,505 lm / 560 W (flood). CRI 90.3–94.5, TLCI up to 94.
    id: 'elation-kl-fresnel-8-fc', name: 'KL Fresnel 8 FC', manufacturer: 'Elation', category: 'fresnel',
    wattage: 560, lumens: 16505, beamAngle: 10.4, fieldAngle: 20.6, cutoffAngle: 29.2,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [10.4, 50.8],
    colorTemp: 0, colorTempRange: [2700, 6500], cri: 92, tlci: 94, weight: 10.5, mountType: 'clamp',
    photometric: { lux: 158522, distance: 1, beamAngle: 10.4, colorTemp: 6500 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 18,
  },
  {
    id: 'elation-kl-fresnel-6-fc', name: 'KL Fresnel 6 FC', manufacturer: 'Elation', category: 'fresnel',
    wattage: 220, lumens: 9000, beamAngle: 12, fieldAngle: 18,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'fresnel', zoomRange: [12, 60],
    colorTemp: 0, colorTempRange: [2000, 10000], cri: 95, tlci: 94, weight: 7.0, mountType: 'clamp',
    photometric: { lux: 7000, distance: 3, beamAngle: 12, colorTemp: 5600 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 18,
  },
  {
    id: 'elation-kl-panel-fc', name: 'KL Panel FC', manufacturer: 'Elation', category: 'led-panel',
    wattage: 295, lumens: 16000, beamAngle: 64, fieldAngle: 90,
    beamShape: 'rectangular', beamRatioWH: 1, lensType: 'fixed',
    colorTemp: 0, colorTempRange: [2000, 10000], cri: 95, tlci: 92, weight: 13.0, mountType: 'clamp',
    photometric: { lux: 13000, distance: 1, beamAngle: 64, colorTemp: 5600 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 16,
  },
  {
    id: 'elation-kl-profile-fc', name: 'KL Profile FC', manufacturer: 'Elation', category: 'profile',
    wattage: 305, lumens: 10600, beamAngle: 6, fieldAngle: 10,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 50],
    colorTemp: 0, colorTempRange: [2400, 8500], cri: 94, tlci: 92, weight: 9.5, mountType: 'clamp',
    photometric: { lux: 15517, distance: 1, beamAngle: 50, colorTemp: 6500 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 24,
  },
  {
    id: 'elation-kl-par-fc', name: 'KL PAR FC', manufacturer: 'Elation', category: 'par',
    wattage: 280, lumens: 11000, beamAngle: 11, fieldAngle: 16,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'interchangeable',
    colorTemp: 0, colorTempRange: [1750, 10000], cri: 93, tlci: 95, weight: 7.7, mountType: 'clamp',
    photometric: { lux: 11520, distance: 5, beamAngle: 11, colorTemp: 6000 },
    powerConnector: 'powerCON TRUE1', dmxChannels: 16,
  },
  {
    id: 'elation-fuze-wash-z350', name: 'Fuze Wash Z350', manufacturer: 'Elation', category: 'moving-wash',
    wattage: 399, lumens: 13000, beamAngle: 6, fieldAngle: 10,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [6, 46],
    colorTemp: 0, colorTempRange: [2700, 8000], cri: 80, weight: 20.4, mountType: 'yoke',
    photometric: { lux: 60280, distance: 2, beamAngle: 6, colorTemp: 7000 },
    powerConnector: 'powerCON TRUE1', ipRating: '30', dmxChannels: 28,
  },
  {
    id: 'elation-fuze-par-z120', name: 'Fuze Par Z120 IP', manufacturer: 'Elation', category: 'moving-wash',
    wattage: 157, lumens: 4500, beamAngle: 7, fieldAngle: 12,
    beamShape: 'circular', beamRatioWH: 1, lensType: 'zoom', zoomRange: [7, 55],
    colorTemp: 0, colorTempRange: [2700, 8000], cri: 80, weight: 10.0, mountType: 'yoke',
    photometric: { lux: 10640, distance: 3, beamAngle: 7, colorTemp: 7000 },
    powerConnector: 'powerCON TRUE1', ipRating: '65', dmxChannels: 20,
  },
];
